#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "schedule.h"
#include "linkedList.h"

/* run this program using the console pauser or add your own getch, system("pause") or input loop */

int main(int argc, char *argv[]) {
	
	int exit_flag = 0;
	FILE *fp;
	
	char name[200];
	char place[100], typeName[100];	
	size_t size;
	int month;
	int day;
	int type;
	void *list;
	void *ndPtr;
	void *schedInfo;
	int option;
	int cnt;
	char ch[100];
	
	//1. FILE pointer open & error handling
	//fill code here ----
	fp = fopen(argv[1], "rb");
	if(fp == NULL)
	{
		printf("file not open\n");
		return -1;
	}
	//initializing the list
	printf("Reading the data files... \n");
	list = (void*)list_genList();


	
	
	//2. read from the file
	while (!feof(fp))
	{	
		fscanf(fp, "%s %s %d %d %d", name, place, &type, &month, &day);
		//fill code here -- generate genSchedInfo structure by genSchedInfo function
		schedInfo = sched_genSchedInfo(name, place, type, month, day);
		//put the scheduling info instance generated by genSchedInfo function
		list_addTail(schedInfo, list);
	}
	
	
	//fill code here ---- close the file pointer
	
	printf("Read done! %i schedules are read\n\n", list_len(list));
	
	
	//program starts
	while(exit_flag == 0) 
	{
		//3. menu printing
		//fill code here ---- 
		printf("1. print all the schedules\n2. serch for schecules in the month\n3. search for schedules in the place\n4. search for specific type schedule\n5. exit\n\n");
		
		//4. get option from keyboard
		//fill code here ----
		printf("select an option : ");
		scanf("%d", &option);
		
		switch(option)
		{
			case 1: //print all the schedules
				printf("printing all the schedules in the scheduler.....\n\n\n");
				printf("------------------------------------------------\n");
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print count and each scheduling info element
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					
					//fill code this part - end			
					sched_print(schedInfo);					
					printf("------------------------------------------------\n");
				}				
				printf("\n\n\n");
				break;
				
			
			case 2:
				printf("which month ? : ");
				scanf("%i", &month);		
			
				printf("\n\n\n------------------------------------------------\n");
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print scheduling info elements matching to the month
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					
					//fill code this part - end
					if(sched_getMonth(schedInfo) == month)						
					{
						sched_print(schedInfo); 						
						printf("------------------------------------------------\n");
					}
				}
				printf("\n\n\n");
				
				break;

			case 3:
				printf("which place ? : ");
				scanf("%s", place);

				printf("\n\n\n------------------------------------------------\n");
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print scheduling info elements matching to the place
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					
					//fill code this part - end					
					if(!strcmp(sched_getPlace(schedInfo),place))	
					{
						sched_print(schedInfo);							
						printf("------------------------------------------------\n");
					}
				}								
				printf("\n\n\n");
				break;
				
			case 4:
				printf("which type ?\n");
				sched_printTypes();
				printf("your choice : ");
				scanf("%s", typeName);
				
				if (sched_convertType(typeName)<=7 && 0<=sched_convertType(typeName))
				{				
					printf("\n\n\n------------------------------------------------\n");
					ndPtr = list;
					while (list_isEndNode(ndPtr) == 0)
					{
						//file code here -- print scheduling info elements matching to the place
						ndPtr = list_getNextNd(ndPtr); //get the next node from the list
						schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
						
						//fill code this part - end						
						if(sched_convertType(typeName) == sched_getType(schedInfo))						
						{
							sched_print(schedInfo); 						
							printf("------------------------------------------------\n");
						}
					}
				}
				else
				{
					printf("\n\n\nwrong type name!\n");
				}				
				printf("\n\n\n");
				break;
				
			case 5:
				printf("Bye!\n\n");
				exit_flag = 1;
				break;
				
			default:
				printf("wrong command! input again\n");
				break;
		}
		
	}

	return 0;
}
